import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import axios from 'axios'

// Axios global setup
axios.defaults.baseURL = process.env.NEXT_PUBLIC_BACKEND_URL;
axios.defaults.headers.post['Content-Type'] = 'application/json';
axios.defaults.headers.patch['Content-Type'] = 'application/json';
axios.defaults.withCredentials = true;
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Js with Payload",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
